// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVx0ZUr_-MLb9NKPBOq5hziMuF2ASel_Q',
    appId: '1:534717963284:web:c35d0917b68ed11258db01',
    messagingSenderId: '534717963284',
    projectId: 'ace-chatapp',
    authDomain: 'ace-chatapp.firebaseapp.com',
    storageBucket: 'ace-chatapp.appspot.com',
    measurementId: 'G-PP3MHF9795',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM6rhG9NHSUnlB_CUq7FORLx3Utz2dLWM',
    appId: '1:534717963284:android:244334c1e945d2cf58db01',
    messagingSenderId: '534717963284',
    projectId: 'ace-chatapp',
    storageBucket: 'ace-chatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVvSbqySEGuDULRwLDS1EIUvewlhpMlfQ',
    appId: '1:534717963284:ios:ca2dc59e9003c82658db01',
    messagingSenderId: '534717963284',
    projectId: 'ace-chatapp',
    storageBucket: 'ace-chatapp.appspot.com',
    iosBundleId: 'com.moace.acechat.aceChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVvSbqySEGuDULRwLDS1EIUvewlhpMlfQ',
    appId: '1:534717963284:ios:ca2dc59e9003c82658db01',
    messagingSenderId: '534717963284',
    projectId: 'ace-chatapp',
    storageBucket: 'ace-chatapp.appspot.com',
    iosBundleId: 'com.moace.acechat.aceChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVx0ZUr_-MLb9NKPBOq5hziMuF2ASel_Q',
    appId: '1:534717963284:web:5e0174170678b42558db01',
    messagingSenderId: '534717963284',
    projectId: 'ace-chatapp',
    authDomain: 'ace-chatapp.firebaseapp.com',
    storageBucket: 'ace-chatapp.appspot.com',
    measurementId: 'G-YY1YP7VGSJ',
  );
}
